In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])

In [3]:
arr

array([1, 2, 3])

In [5]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [6]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a = np.array([[1,2,5], [6,3,5]], dtype = np.int8)

In [9]:
a.dtype

dtype('int8')

In [10]:
arr2.dtype

dtype('int32')

In [11]:
arr.dtype

dtype('int32')

In [12]:
arr2.shape

(3, 3)

In [13]:
arr2.size

9

In [14]:
arr.size

3

In [15]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr2[2][2]

9

In [17]:
arr2[1][1]

5

In [18]:
arr2[2][2] = 99

In [19]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 99]])

In [20]:
zeros = np.zeros((2,4))

In [21]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
ones = np.ones((2,3))

In [23]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
arange = np.arange(9)

In [25]:
arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
arlin = np.linspace(1, 10, 5)

In [27]:
arlin

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
x = np.linspace(1, 4, 4)

In [29]:
x

array([1., 2., 3., 4.])

In [39]:
empty = np.empty((3,3), dtype= np.int8)

In [40]:
empty.dtype

dtype('int8')

In [41]:
empty

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [42]:
empty

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [43]:
identity = np.identity(3)

In [44]:
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
arange.size

9

In [49]:
arange.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
arange.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
x = np.arange(12)

In [54]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
x.size

12

In [56]:
x.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [57]:
x.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [58]:
x.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [59]:
arr

array([1, 2, 3])

In [60]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 99]])

In [65]:
axisarr = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [66]:
axisarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
np.sum(axisarr, axis = 0)

array([12, 15, 18])

In [68]:
np.sum(axisarr, axis = 1)

array([ 6, 15, 24])

In [69]:
arr

array([1, 2, 3])

In [70]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 99]])

In [71]:
arr.ndim

1

In [73]:
arr2.ndim

2

In [74]:
x = np.array([[1, 2, 3], [0, 8 , 69], [69, 5, 8]])

In [75]:
x

array([[ 1,  2,  3],
       [ 0,  8, 69],
       [69,  5,  8]])

In [76]:
x.argmax()

5

In [77]:
x.argmin()

3

In [78]:
x.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [79]:
x.argmin(axis=0)

array([1, 0, 0], dtype=int64)

In [80]:
x

array([[ 1,  2,  3],
       [ 0,  8, 69],
       [69,  5,  8]])

In [81]:
x.argmax(axis= 1)

array([2, 2, 0], dtype=int64)

In [82]:
x.argmin(axis = 1)

array([0, 0, 1], dtype=int64)

In [83]:
x.sort()

In [84]:
x

array([[ 1,  2,  3],
       [ 0,  8, 69],
       [ 5,  8, 69]])

In [85]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 99]])

In [87]:
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
arr2+identity

array([[  2.,   2.,   3.],
       [  4.,   6.,   6.],
       [  7.,   8., 100.]])

In [90]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

In [91]:
arr2 * identity

array([[ 1.,  0.,  0.],
       [ 0.,  5.,  0.],
       [ 0.,  0., 99.]])

In [92]:
np.sqrt(arr2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 9.94987437]])

In [93]:
np.sum(arr2)

135

In [94]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 99]])

In [95]:
np.where( arr2 > 5 )

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [96]:
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [97]:
np.count_nonzero(identity)

3

In [101]:
pyar = [1, 2, 3]

In [102]:
pyar

[1, 2, 3]

In [103]:
npar = np.array(pyar)

In [104]:
npar

array([1, 2, 3])

In [105]:
import sys

In [106]:
sys.getsizeof(1) * len(pyar)

84

In [107]:
npar.itemsize * npar.size

12